// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AssignRoleInput struct {
	UserID string `json:"userId"`
	RoleID string `json:"roleId"`
}

type AuthResponse struct {
	Token        string  `json:"token"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type CreateRoleInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Role struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type UpdateRoleInput struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type UpdateUserInput struct {
	ID          string  `json:"id"`
	Email       *string `json:"email,omitempty"`
	Name        *string `json:"name,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type User struct {
	ID          string  `json:"id"`
	Email       string  `json:"email"`
	Name        *string `json:"name,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	IsActive    bool    `json:"isActive"`
	Roles       []*Role `json:"roles"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}
