package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/androsyz/nexus-user-svc/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, request model.RegisterRequest) (*model.AuthResponse, error) {
	return r.ucAuth.Register(ctx, request)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, request model.LoginRequest) (*model.AuthResponse, error) {
	return r.ucAuth.Login(ctx, request)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthResponse, error) {
	return r.ucAuth.RefreshToken(ctx, refreshToken)
}

// VerifyToken is the resolver for the verifyToken field.
func (r *mutationResolver) VerifyToken(ctx context.Context, token string) (bool, error) {
	return r.ucAuth.VerifyToken(ctx, token)
}

// RevokeToken is the resolver for the revokeToken field.
func (r *mutationResolver) RevokeToken(ctx context.Context) (bool, error) {
	return r.ucAuth.RevokeToken(ctx)
}
